SET SERVEROUTPUT ON;
SET VERIFY OFF;


--USER DEFINED EXCEPTIONS

DECLARE
	A NUMBER := 20;
	B NUMBER := &X;
	res NUMBER;
	
	userDefException EXCEPTION;
	
BEGIN		
	IF B = 0 THEN
		RAISE userDefException;
	END IF;
	
	res := A/B;
	DBMS_OUTPUT.PUT_LINE(res);


EXCEPTION
	WHEN userDefException THEN
		DBMS_OUTPUT.PUT_LINE('DIVISOR IS ZERO');
END;
/




DECLARE
	A money.taka%TYPE;
	B NUMBER := &X;
	val number;
	userDefException EXCEPTION;
	
BEGIN	
	SELECT taka into A from money where id=1;
	
	IF B<0 THEN
		RAISE userDefException;
	END IF;
	val:= A/B;

EXCEPTION
	WHEN userDefException THEN
		DBMS_OUTPUT.PUT_LINE('DIVISOR IS NEGATIVE');
		B:= B*(-1);
		val := A/B;
		DBMS_OUTPUT.PUT_LINE(val);
		
	WHEN TOO_MANY_ROWS THEN
		DBMS_OUTPUT.PUT_LINE('MANY ROWS DETECTED');
		
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND');
	
	WHEN ZERO_DIVIDE THEN
		DBMS_OUTPUT.PUT_LINE('CANNOT DIVIDE BY ZERO');
	
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('OTHER ERRORS FOUND');
	
END;
/