SET SERVEROUTPUT ON;
SET VERIFY OFF;

--RAISE_APPLICATION_ERROR

DECLARE
	A NUMBER := 20;
	B NUMBER := &X;
	res NUMBER;
	
BEGIN		
	IF B = 0 THEN
		RAISE_APPLICATION_ERROR(-20008, 'DIVISOR IS ZERO');
	END IF;
	
	res := A/B;
	DBMS_OUTPUT.PUT_LINE(res);

EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/


--Exception propagation

DECLARE
	A NUMBER := 20;
	B NUMBER := &X;
	res NUMBER;
	
	e1 EXCEPTION;
    PRAGMA exception_init (e1, -20007);
	
BEGIN		
	IF B = 0 THEN
		RAISE_APPLICATION_ERROR(-20007, 'DIVISOR IS ZERO');
	END IF;
	
	res := A/B;
	DBMS_OUTPUT.PUT_LINE(res);

EXCEPTION
	WHEN e1 THEN
		DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/