SET SERVEROUTPUT ON;

--STATEMENT-LEVEL TRIGGER 

CREATE OR REPLACE TRIGGER HELLO3 
AFTER UPDATE ON emp

BEGIN
	DBMS_OUTPUT.PUT_LINE('Updated');
END;
/

UPDATE emp SET salary = 140 where id=5;
UPDATE emp SET name = 'X' where id=4;


--ROW LEVEL TRIGGER

CREATE OR REPLACE TRIGGER HELLO5 
AFTER UPDATE 
OF salary
ON emp
FOR EACH ROW
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO5');
END;
/

UPDATE emp SET salary = 100;
UPDATE emp SET salary = 100 WHERE ID = 10;
SELECT * FROM emp;