--IMPLEMENTING BODY OF A PACKAGE

CREATE OR REPLACE PACKAGE BODY mypack AS

	FUNCTION F1(A1 IN NUMBER)
	RETURN NUMBER
	IS 
	
	BEGIN
		IF MOD(A1, 2) = 0 THEN
			RETURN 1;
		ELSE
			RETURN 0;
		END IF;
	END F1;
	
	PROCEDURE P1(B1 IN NUMBER)
	IS
	
	BEGIN
		IF MOD(B1, 2) = 0 THEN
			DBMS_OUTPUT.PUT_LINE('EVEN');
		ELSE
			DBMS_OUTPUT.PUT_LINE('ODD');
		END IF;
	END P1;
	
END mypack;
/