SET SERVEROUTPUT ON;

--CASE-WHEN-ELSE

DECLARE
	NUM INT:=5;
	
BEGIN
	CASE
		WHEN MOD(NUM,3) = 0 THEN
			DBMS_OUTPUT.PUT_LINE('ZERO');
		WHEN MOD(NUM,3) = 1 THEN
			DBMS_OUTPUT.PUT_LINE('ONE');
		ELSE
			DBMS_OUTPUT.PUT_LINE('TWO');
	END CASE;
END;
/



DECLARE
	NUM EMP.salary%TYPE; 
	
BEGIN
	SELECT salary INTO NUM FROM EMP WHERE id=1;
	CASE
		WHEN MOD(NUM,3) = 0 THEN
			DBMS_OUTPUT.PUT_LINE('ZERO');
		WHEN MOD(NUM,3) = 1 THEN
			DBMS_OUTPUT.PUT_LINE('ONE');
		ELSE
			DBMS_OUTPUT.PUT_LINE('TWO');
	END CASE;
	
END;
/



--CASE-WHEN-ELSE: DIFFERENT FORMAT

DECLARE 
   grade CHAR(1) := 'A'; 
BEGIN 
   CASE grade 
      WHEN 'A+' THEN DBMS_OUTPUT.PUT_LINE('80-100'); 
      WHEN 'A'  THEN DBMS_OUTPUT.PUT_LINE('70-79'); 
      WHEN 'A-' THEN DBMS_OUTPUT.PUT_LINE('60-69'); 
      WHEN 'B'  THEN DBMS_OUTPUT.PUT_LINE('50-59'); 
      WHEN 'F'  THEN DBMS_OUTPUT.PUT_LINE('FAIL'); 
      ELSE  DBMS_OUTPUT.PUT_LINE('NO SUCH GRADE'); 
   END CASE; 
END; 
/



DECLARE
	NUM emp.salary%TYPE; 
BEGIN
	SELECT salary INTO NUM FROM EMP WHERE id=1;
	
	CASE MOD(NUM,3)
		WHEN 0 THEN
			DBMS_OUTPUT.PUT_LINE('ZERO');
		WHEN 1 THEN
			DBMS_OUTPUT.PUT_LINE('ONE');
		ELSE
			DBMS_OUTPUT.PUT_LINE('TWO');
	END CASE;
	
END;
/
